/**
 * Protocol module exports
 */

export {
  COMMAND_ACTIVATE,
  COMMAND_READY,
  COMMAND_AUTH,
  COMMAND_AUTH_RESULT,
  COMMAND_AUTH_INIT,
  COMMAND_ACTIVATED,
  COMMAND_AUTH_DECLINED,
  COMMAND_AUTH_TIMEOUT,
  COMMAND_RECONNECT,
  COMMAND_CONNECTION_FAILED,
  COMMAND_ERROR,
  COMMAND_HEALTH,
  SOCKET_PING_TIMEOUT,
  AUTHORIZATION_TIME_FRAME,
  DEFAULT_PORT,
  STATUS,
  DECLINE_REASON,
} from './constants.js';

export { TrustGateClient } from './trust-gate-client.js';
